
#include "TIMER1Test.h"

extern void TIMER1Test ()
{
	DIO_Init();
	TIMER1_Init(TIMER1_NORMAL_MODE,  TIMER1_PRESCALER_8);
	//TIMER1_OC1AMode(TIMER1_OC1_SET);
	//TIMER1_OC1BMode(TIMER1_OC1_CLEAR);
	TIMER1_TopSet_OC1AFree(999);
	TIMER1_CompareUnit1BSet(999);
	
	
}