
#include "DIO_interface.h"

const DIO_PinStatus_type PinsStatusArray[] = {
	OUTPUT, //PINA0
	OUTPUT, //PINA1
	OUTPUT, //PINA2
	OUTPUT, //PINA3
	OUTPUT, //PINA4
	OUTPUT, //PINA5
	OUTPUT, //PINA6
	OUTPUT, //PINA7
	OUTPUT, //PINB0
	OUTPUT, //PINB1
	OUTPUT, //PINB2
	OUTPUT, //PINB3
	OUTPUT, //PINB4
	OUTPUT, //PINB5
	OUTPUT, //PINB6
	OUTPUT, //PINB7
	OUTPUT, //PINC0
	OUTPUT, //PINC1
	OUTPUT, //PINC2
	OUTPUT, //PINC3
	INPULL, //PINC4
	INPULL, //PINC5
	INPULL, //PINC6
	INPULL, //PINC7
	OUTPUT, //PIND0
	OUTPUT, //PIND1
	OUTPUT, //PIND2
	OUTPUT, //PIND3
	OUTPUT, //PIND4
	OUTPUT, //PIND5
	OUTPUT, //PIND6
	OUTPUT  //PIND7
};

