
#include "DIO_interface.h"

const DIO_PinStatus_type PinsStatusArray[] = {
	INFREE, //PINA0
	INFREE, //PINA1
	INFREE, //PINA2
	OUTPUT, //PINA3
	OUTPUT, //PINA4
	OUTPUT, //PINA5
	OUTPUT, //PINA6
	INFREE, //PINA7
	OUTPUT, //PINB0
	OUTPUT, //PINB1
	INPULL, //PINB2
	OUTPUT, //PINB3
	OUTPUT, //PINB4
	OUTPUT, //PINB5
	OUTPUT, //PINB6
	OUTPUT, //PINB7
	OUTPUT, //PINC0
	OUTPUT, //PINC1
	OUTPUT, //PINC2
	OUTPUT, //PINC3
	OUTPUT, //PINC4
	OUTPUT, //PINC5
	OUTPUT, //PINC6
	OUTPUT, //PINC7
	INFREE, //PIND0
	OUTPUT, //PIND1
	INPULL, //PIND2
	OUTPUT, //PIND3
	OUTPUT, //PIND4
	OUTPUT, //PIND5
	OUTPUT, //PIND6
	OUTPUT  //PIND7
};

